
spring:
  datasource:
    platform: mysql
    #    url: jdbc:mysql://192.168.2.122:3307/shopTbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/shopTbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:  root
    password:  root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  mvc:
    view:
      prefix:  /jsp/
      suffix: .jsp
      static-path-pattern: /webapp/**
  resources:
    static-locations: classpath:/webapp


mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:com/mall/dao/*/*.xml
  type-aliases-package: com.mall.entity

server:
  port: 9999
